version: '3.8'
services:
  devcontainer:
    image: mcr.microsoft.com/devcontainers/base:ubuntu
    volumes:
      - ../..:/workspaces:cached
    # network_mode: service:redis
    command: sleep infinity
    networks:
      - dev_network

  # ---------
  # | REDIS |
  # ---------
  redis:
    image: redis:7.0.10
    container_name: "redis"
    restart: unless-stopped     # "unless-stopped" or "always"
    ## UNCOMMENT THESE LINES IF WE USE CUSTOM REDIS CONFIG ##
    volumes:
      - redis-data:/data
    networks:
      - dev_network

  # ---------------
  # | REDIS STACK |
  # ---------------
  redis_stack:
    image: redis/redis-stack-server:7.0.6-RC8
    container_name: "redis_stack"
    restart: unless-stopped     # "unless-stopped" or "always"
    ## UNCOMMENT THESE LINES IF WE USE CUSTOM REDIS CONFIG ##
    volumes:
      - redis-stack-data:/data
    networks:
      - dev_network

volumes:
  redis-data:
  redis-stack-data:
  
networks:
  dev_network:
    name: dev-network
